### ISSUE TITLE
Action: download tree_metadata_DOE_plus_vales.csv  and incorporate into code

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/Calloc_TreeRingNPP#14]
Action: download tree_metadata_DOE_plus_vales.csv  and incorporate into code
see #6 https://github.com/davidjpmoore/Calloc_TreeRingNPP/issues/6

**Comment by davidjpmoore** [comment]
Looks like it's working now
![capture](https://cloud.githubusercontent.com/assets/6138344/8529872/74d3caa6-23d2-11e5-87a9-972cc640634c.PNG)

one error:

> # Run the GAMM for the missing trees; right now we're smoothing by individual plot
> 
> gamm.missing <- gapfill.gamm(data=fill.missing, DBH="DBH..cm.", Species.Use="Species.Model", Canopy.Class="Canopy.Class", smooth.by="PlotID", canopy=T, out.prefix=out.path)
> Error in pdf(paste0(out.prefix, "_gapfill.pdf"), height = 7.5, width = 10) : 
>   cannot open file 'processed_data/GapFill_Metadata/MissingTrees_gapfill.pdf'
> 
> data.all[data.all$Measured=="NO", "RW.modeled"] <- gamm.missing$data[gamm.missing$data$Measured=="NO", "RW.modeled"] # Note: this will rewrite the modeled values in data.all even if we had previously gap-filled them (this is a good thing)
> Error: object 'gamm.missing' not found

**Comment by alexanderm10** [comment]
It seems to have run from scratch for me.  There are a few places in the code where we have to make some choices in what to do.  ex. # ---------------
 Select your site codes
**PAY ATTENTION HERE: YOU HAVE A CHOICE TO MAKE!**
_sites.ring.data <- unique(substr(ring.data$PlotID,1,2))_

# If starting from scratch:

_site.codes <- sites.ring.data_

# If adding new sites select those that haven't already been gapfilled

_site.codes <- sites.ring.data[!(sites.ring.data %in% unique(substr(rings.filled$PlotID,1,2)))]_

this is from line 217-228 in the 2_gapfilling script.  In this case you will be starting from scratch so you run line 224 but NOT line 227.  Christy has made it so that we can incrementally add sites without re-running the gamm for everything.  Doing this decreases computation time.  It should run if you select the start from scratch options.

**Comment by alexanderm10** [comment]
Whoa... I now realize that the issues text is markdown supported (and I now know what that means)... *so much bold*

**Comment by crollinson** [comment]
Just FYI, you can edit your comments to help get rid of Github's automatic formatting things.  Usually removing # signs and/or adjusting spaces or the lines of dashes that I tend to use to separate section of code fixes the problem
